config/routes.rb
Rails.application.routes.draw do
  devise_for :companies, controllers: {
  sessions:      'companies/sessions',
  passwords:     'companies/passwords',
  registrations: 'companies/registrations'
  }

  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
  }

  resources :companies, only: [:index, :show]
  resources :offers do
    member do
      get :situation
    end
    resources :comments, only: [:create]
    resources :replies, only: [:create]
    resources :applies, only: [:new, :create]
  end
  resources :users, only: [:index, :show]
  root "offers#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/apply.rb
class Apply < ApplicationRecord
  belongs_to :user
  belongs_to :offer
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :offer
  belongs_to :user

  validates :text, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :offers
  has_many :replies
end

app/models/offer.rb
class Offer < ApplicationRecord
  mount_uploader :image, ImagesUploader
  paginates_per 5

  belongs_to :company

  has_many :applies
  has_many :users, through: :applies
  has_many :comments
  has_many :replies

  accepts_nested_attributes_for :applies
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :offer
  belongs_to :company
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :applies
  has_many :offers, through: :applies
  has_many :comments
  accepts_nested_attributes_for :applies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/applies_controller.rb
class AppliesController < ApplicationController

  before_action :authenticate_user!

  def new
    @offer = Offer.find(params[:offer_id])
    @apply = Apply.new
  end

  def create
    @offer = Offer.find(params[:offer_id])
    @apply = Apply.new(offer_id: apply_params[:offer_id], user_id: current_user.id)
    if @apply.save
      redirect_to root_path, flash: {notice: '応募が完了しました'}
    else
      flash.now[:alert] = '応募に失敗しました。'
      redirect_to root_path
    end
  end

  def show
    @offer = Offer.find(params[:offer_id])
    @apply = Apply.find(params[:id])
  end

  private
  def apply_params
    params.permit(:user_id, :offer_id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.create(text: comment_params[:text], offer_id: comment_params[:offer_id], user_id: current_user.id)
    redirect_to "/offers/#{@comment.offer.id}"
  end

  private
  def comment_params
    params.permit(:text, :offer_id)
  end
end

app/controllers/companies/sessions_controller.rb
class Companies::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/companies/unlocks_controller.rb
class Companies::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @company = Company.new
  end

  def show
    @company = Company.find(params[:id])
    @offers = Offer.where(company_id: @company.id)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  before_action :set_offers
  before_action :authenticate_company!, only: [:new]

  def index
    @offers = Offer.order("created_at DESC").page(params[:page]).per(5)
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = current_company.offers.new(offer_params)
    if @offer.save
      redirect_to offers_path
    end
  end

  def destroy
    offer = Offer.find(params[:id])
    offer.destroy if offer.company_id == current_company.id
  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def update
    offer = Offer.find(params[:id])
    if offer.company_id == current_company.id
      offer.update(offer_params)
    end
  end

  def show
    @offer = Offer.find(params[:id])
    @offer_id = Offer.find(params[:id]).id
    @apply = Apply.new
    @comments = @offer.comments.includes(:user)
    @replies = @offer.replies.includes(:company)
  end

  def situation
    @offer = Offer.find(params[:id])
    @applies = Apply.where(offer_id: @offer.id)
  end

  private

  def offer_params
    params.require(:offer).permit(:title, :image,:what, :why, :how,{ user_ids:[]})
  end

  def set_offers
    @company = Company.new
  end

end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def create
     @reply = Reply.create(text: reply_params[:text], offer_id: reply_params[:offer_id], company_id: current_company.id)
     redirect_to "/offers/#{@reply.offer.id}"
   end

   private
   def reply_params
     params.permit(:text, :offer_id)
   end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @applies = Apply.where(user_id: @user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flashmessage.html.haml
- flash.each do |key, value|
  - key = "info" if key == "notice"
  - key = "danger"  if key == "alert"
  = content_tag :div, value, class: "alert alert-#{key}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Wantedly
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'true'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'true'
  %body
    = render "layouts/flashmessage"
    = yield

app/views/shared/_header.html.haml
.header
  %p.header-logo
    = link_to image_tag("https://de7iszmjjjuya.cloudfront.net/assets/wantedly-logo-5906d9a368d0bcdd2919553127357d4d.svg"), offers_path
  .menu
    %ul.user-menus
      %li.user-menu
        =link_to new_user_session_path do
          %p ログイン
      %li.user-menu
        =link_to edit_user_registration_path do
          %p プロフィール
      - if user_signed_in?
        %li.user-menu
          =link_to user_path(current_user.id) do
            %p マイページ
      %li.user-menu
        =link_to new_company_session_path do
          %p 採用担当の方はこちらから
      %li.user-menu
        =link_to edit_company_registration_path do
          %p 企業プロフィール
      %li.user-menu
        =link_to new_offer_path do
          %p 記事を投稿する
      - if company_signed_in?
        %li.user-menu
          =link_to company_path(current_company.id) do
            %p 求人を管理する
    = form_for @company do |f|
      .search-form__field
        = f.text_field :name, placeholder: "人や会社、募集を検索"

app/views/shared/_header_show.html.haml
.header
  %p.header-logo
    = link_to image_tag("https://de7iszmjjjuya.cloudfront.net/assets/wantedly-logo-5906d9a368d0bcdd2919553127357d4d.svg"), offers_path
  .menu
    %ul.user-menus
      %li.user-menu
        =link_to new_user_session_path do
          %p ログイン
      %li.user-menu
        =link_to edit_user_registration_path do
          %p プロフィール
      - if user_signed_in?
        %li.user-menu
          =link_to user_path(current_user.id) do
            %p マイページ
      %li.user-menu
        =link_to new_company_session_path do
          %p 採用担当の方はこちらから
      %li.user-menu
        =link_to edit_company_registration_path do
          %p 企業プロフィール
      %li.user-menu
        =link_to new_offer_path do
          %p 求人を投稿する
      - if company_signed_in?
        %li.user-menu
          =link_to company_path(current_company.id) do
            %p 求人を管理する