config/routes.rb
Rails.application.routes.draw do
  devise_for :companies, controllers: {
  sessions:      'companies/sessions',
  passwords:     'companies/passwords',
  registrations: 'companies/registrations'
  }

  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
  }

  resources :companies, only: [:index, :show]
  resources :offers do
    member do
      get :situation
    end
    resources :comments, only: [:create]
    resources :replies, only: [:create]
    resources :applies, only: [:new, :create]
  end
  resources :users, only: [:index, :show]
  root "offers#index"

end

app/models/offer.rb
class Offer < ApplicationRecord
  mount_uploader :image, ImagesUploader
  paginates_per 5

  belongs_to :company

  has_many :applies
  has_many :users, through: :applies
  has_many :comments
  has_many :replies

  accepts_nested_attributes_for :applies
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  before_action :set_offers
  before_action :authenticate_company!, only: [:new]

  def index
    @offers = Offer.order("created_at DESC").page(params[:page]).per(5)
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = current_company.offers.new(offer_params)
    if @offer.save
      redirect_to offers_path
    end
  end

  def destroy
    offer = Offer.find(params[:id])
    offer.destroy if offer.company_id == current_company.id
  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def update
    offer = Offer.find(params[:id])
    if offer.company_id == current_company.id
      offer.update(offer_params)
    end
  end

  def show
    @offer = Offer.find(params[:id])
    @offer_id = Offer.find(params[:id]).id
    @apply = Apply.new
    @comments = @offer.comments.includes(:user)
    @replies = @offer.replies.includes(:company)
  end

  def situation
    @offer = Offer.find(params[:id])
    @applies = Apply.where(offer_id: @offer.id)
  end

  private

  def offer_params
    params.require(:offer).permit(:title, :image,:what, :why, :how,{ user_ids:[]})
  end

  def set_offers
    @company = Company.new
  end

end

app/views/offers/_offer.html.haml
.project-image
  = image_tag offer.image
.project-detail
  .project-label
    -# %span
    -#   = offer.job_type
  %h1.project-title
    = link_to "/offers/#{offer.id}", method: :get do
      %span
        = offer.title
  .project-bottom
    %table{role: "presentation"}
      %tbody
        %tr
          %td.company-name
            %h3
              = offer.company.name
            -# %span
            -#   = offer.region

app/views/offers/destroy.html.haml
.container
  = render partial: "shared/header_show"
  #account-page.account-page
    .account-page__header
      %h2 削除が完了しました。

app/views/offers/edit.html.haml
.container
  = render partial: "shared/header"
  .registrations-body
    .main-body
      %h1.title 投稿する
      .company-form
        = form_for @offer do |f|
          .company-form__field
            .company-form__field--left
              = f.label :title, "タイトル", class: "form-label"
            .company-form__field--right
              = f.text_field :title, placeholder: "タイトルを入力してください", autocomplete: "off", class: "form-input"
          .company-form__field
            .company-form__field--left
              = f.label :image, "メイン画像", class: "form-label"
            .company-form__field--right
              = f.file_field :image, class: "form-logo"
          .company-form__field
            .company-form__field--left
              = f.label :what, "何をやっているのか", class: "form-label"
            .company-form__field--right
              = f.text_field :what, placeholder: "東京都新宿区歌舞伎町で不動産業を営んでおります。", autocomplete: "off", class: "form-input"
          .company-form__field
            .company-form__field--left
              = f.label :why, "なぜやるのか", class: "form-label"
            .company-form__field--right
              = f.text_field :why, placeholder: "それは本当不思議ですよね。自分でもわからないんですから", autocomplete: "off", class: "form-input"
          .company-form__field
            .company-form__field--left
              = f.label :how, "こんなことやります", class: "form-label"
            .company-form__field--right
              = f.text_field :how, placeholder: "歌舞伎町で朝からけん玉大会", autocomplete: "off", class: "form-input"

          .company-form__field
            .submit-action
              = f.submit "投稿する", class: "btn"

app/views/offers/index.html.haml
.container
  = render partial: "shared/header"
  .top-projects
    .top-projects__details
      .projects-cover
        %image{src: "https://d2v9k5u4v94ulw.cloudfront.net/small_light(dw=640,dh=262,da=s,ds=s,cw=640,ch=262,cc=FFFFFF)/assets/images/366004/original/307d3ec0-7a75-4fe9-aa99-bd61e950c252.jpeg?1461328266"}
      .job-type
        %p
      .title
        %h2 くらしの経済メディアMONEY PLUS」の編集者・ディレクター募集
      .company-name
        %img{src: "https://d2v9k5u4v94ulw.cloudfront.net/small_light(dw=62,dh=62,da=s,ds=s,cw=62,ch=62,cc=FFFFFF)/assets/images/3893/original/49ef9acc-c4d9-4b98-8a36-0856b8e0e586.png?1411809805"}
        %p 株式会社マネーフォワード
    .top-projects__details
      .projects-cover
        %image{src: "https://d2v9k5u4v94ulw.cloudfront.net/small_light(dw=640,dh=262,da=s,ds=s,cw=640,ch=262,cc=FFFFFF)/assets/images/1187311/original/caf99920-1d87-4564-a167-e604d92c0bc1.jpeg?1485940572"}
      .job-type
        %p
      .title
        %h2 2018年新卒 書籍買い放題、セミナー受け放題。勉強好きSEを募集
      .company-name
        %img{src: "https://d2v9k5u4v94ulw.cloudfront.net/small_light(dw=50,dh=50,da=l,ds=s,cc=FFFFFF)/assets/images/20002/original/34a7a20c-8b78-4f6c-af84-3885841b6e49.jpeg?1400660438"}
        %p 株式会社キャパ
    .top-projects__details
      .projects-cover
        %image{src: "https://d2v9k5u4v94ulw.cloudfront.net/small_light(dw=640,dh=262,da=s,ds=s,cw=640,ch=262,cc=FFFFFF)/assets/images/81663/original/00a137bf-a8cb-4349-b599-60cbecb5a3d5.jpeg?1490516448"}
      .job-type
        %p
      .title
        %h2 企業向け先端ソフトウェアのエンジニアと営業(東京と大阪)
      .company-name
        %img{src: "https://d2v9k5u4v94ulw.cloudfront.net/small_light(dw=50,dh=50,da=l,ds=s,cc=FFFFFF)/assets/images/112075/original/35e1630c-fbb6-4786-a91e-0219096c9c6f.png?1434273615"}
        %p 株式会社クライム
  .body
    .column-side
      .project-index-filter-category
        .project-index-filter-category-title
          %h5 職種
          %ul
            %li.category
              %p エンジニア
            %li.category
              %p デザイナー
            %li.category
              %p ディレクター
            %li.category
              %p コーポレート・スタッフ
            %li.category
              %p セールス
            %li.category
              %p マーケティング
            %li.category
              %p ライター
            %li.category
              %p その他
      .project-index-filter-category
        .project-index-filter-category-title
          %h5 採用形態
          %ul
            %li.category
              %p 新卒採用
            %li.category
              %p インターン・学生バイト
            %li.category
              %p 中途採用
            %li.category
              %p 社会人バイト・契約・委託
      .project-index-filter-category
        .project-index-filter-category-title
          %h5 地域
          %ul
            %li.category
              %p 東京
            %li.category
              %p 大阪
            %li.category
              %p 名古屋
            %li.category
              %p 京都
            %li.category
              %p 福岡
            %li.category
              %p 札幌
            %li.category
              %p 北海道・東北
            %li.category
              %p 関東
            %li.category
              %p 北陸・甲信越
            %li.category
              %p 東海
            %li.category
              %p 近畿
            %li.category
              %p 中国・四国
            %li.category
              %p 九州・沖縄
      .project-index-filter-category
        .project-index-filter-category-title
          %h5 特徴
          %ul
            %li.category
              %p TechCrunchに掲載実績あり
            %li.category
              %p 海外進出している
            %li.category
              %p 1億円以上の資金を調達済み
            %li.category
              %p Wantedlyに初登場
            %li.category
              %p 社長が20代
            %li.category
              %p 社長がプログラミングできる
            %li.category
              %p 3000万円以上の資金を調達済み
            %li.category
              %p Skypeで話を聞ける
            %li.category
              %p 留学生さん歓迎
            %li.category
              %p 週末からのコミットでもOK
            %li.category
              %p 友達と一緒に訪問OK
            %li.category
              %p 学生さんも歓迎
            %li.category
              %p ランチをご馳走します
    .column-main
      .projects-index-menu
        %p.projects-count
          %span.current
          %span.per
          %span.total
        %ul.projects-index-sort-menu
          %li.sort-menu
            %p 人気
          %li.sort-menu
            %p 新着
          %li.sort-menu
            %p おすすめ
          %li.sort-menu
            %h4 並び替え
      .projects-index-list
        .project-index-single
          - @offers.each do |offer|
            = render partial: "offer", locals: {offer: offer }
          = paginate @offers

app/views/offers/new.html.haml
.container
  = render partial: "shared/header"
  .registrations-body
    .main-body
      %h1.title 投稿する
      .company-form
        = form_for @offer do |f|
          .company-form__field
            .company-form__field--left
              = f.label :title, "タイトル", class: "form-label"
            .company-form__field--right
              = f.text_field :title, placeholder: "タイトルを入力してください", autocomplete: "off", class: "form-input"
          .company-form__field
            .company-form__field--left
              = f.label :image, "メイン画像", class: "form-label"
            .company-form__field--right
              = f.file_field :image, class: "form-logo"
          .company-form__field
            .company-form__field--left
              = f.label :what, "何をやっているのか", class: "form-label"
            .company-form__field--right
              = f.text_field :what, placeholder: "東京都新宿区歌舞伎町で不動産業を営んでおります。", autocomplete: "off", class: "form-input"
          .company-form__field
            .company-form__field--left
              = f.label :why, "なぜやるのか", class: "form-label"
            .company-form__field--right
              = f.text_field :why, placeholder: "それは本当不思議ですよね。自分でもわからないんですから", autocomplete: "off", class: "form-input"
          .company-form__field
            .company-form__field--left
              = f.label :how, "こんなことやります", class: "form-label"
            .company-form__field--right
              = f.text_field :how, placeholder: "歌舞伎町で朝からけん玉大会", autocomplete: "off", class: "form-input"

          .company-form__field
            .submit-action
              = f.submit "投稿する", class: "btn"

app/views/offers/show.html.haml
.container
  = render partial: "shared/header"
  .projects-show
    .projects-show--header
      -# .projects-show--header__job-type
        %span.icon-job-type
          -# = @offer.job_type
      .projects-show--header__title
        %h1
          = @offer.title
      %h2.projects-show--header__company-name
        %span.company-logo
          -# = image_tag @product.company.logo
        %p.company-name
          = @offer.company.name
      .projects-show--header__image
        = image_tag @offer.image
    .projects-show--body
      .projects-show--body--main
        .descriptions
          %section.projects-show-main-section
            %header
              %h3 なにをやっているのか
              = @offer.what
            .section-body
              %ul.section-images
        .descriptions
          %section.projects-show-main-section
            %header
              %h3 なぜやるのか
              = @offer.why
            .section-body
              %ul.section-images
        .descriptions
          %section.projects-show-main-section
            %header
              %h3 どうやっているのか
              = @offer.how
      .projects-show--body--side
        .projects-show--body--side__action-btn
          .entry-btn
            %span= link_to '話を聞きに行きたい', new_offer_apply_path(params[:id])
          .bookmark-btn
            %span あとで見る
        .projects-show--body--side__map
          %h4 住所
          %p.address
            = @offer.company.address
    .container2
    .comments
      %h4 ＜コメント一覧＞
      - if @comments
        - @comments.each do |comment|
          %p
            %strong
              = link_to comment.user.name, "/users/#{comment.user_id}"
            = comment.text
      - if @replies
        - @replies.each do |reply|
          %p
            %strong
              = reply.company.name
            = reply.text
      - if current_user
        = form_tag("/offers/#{@offer_id}/comments", method: :post) do
          %textarea{:cols => "30", :name => "text", :placeholder => "コメントする", :rows => "2"}
          %input{:type => "submit", :value => "SENT"}/
      - if current_company
        = form_tag("/offers/#{@offer_id}/replies", method: :post) do
          %textarea{:cols => "30", :name => "text", :placeholder => "コメントする", :rows => "2"}
          %input{:type => "submit", :value => "SENT"}/

app/views/offers/situation.html.haml
.container
  = render partial: "shared/header_show"
  #account-page.account-page
    .account-page__header
      %h2
        = @offer.title
        への応募一覧
    .account-page__inner
      %ul.more_list
      - @applies.each do |apply|
        %li
          = apply.user.name
        %p
          = apply.user.email

app/views/offers/update.html.haml
.container
  = render partial: "shared/header_show"
  #account-page.account-page
    .account-page__header
      %h2 更新が完了しました。